import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout/Layout'
import styles from '../styles/Home.module.css'
import { Table,Button } from 'react-bootstrap'
import { useEffect, useState } from 'react'

const baseUrl='http://localhost:3000/api/produtos'
export default function Home() {
  const [produtos,setProdutos]=useState([])
  const [codigo,setCodigo]=useState('');
  
  useEffect(()=>{
    setInterval(()=>{fetch(baseUrl)
      .then((res)=>res.json())
      .then((res)=>{setProdutos(res)})
      .catch((err)=>{console.log(err)})
      
    
    },5000)
    
   },[])
  function renderTable(){
    return (             
        <Table striped bordered hover variant="dark">
            <thead>
                <tr>
                    <th>Codigo</th>
                    <th>Descrição</th>
                    <th>Marca</th>
                    <th>Tamanho</th>
                    <th>Quantidade</th>
                    <th>Preço custo</th>
                    <th>Preço venda</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {renderRows()}
            </tbody>
        </Table>
    )
}

function renderRows(){
  return produtos?.map((produtos,i)=>{
      return  (
          <tr key={produtos.codigo}> 
          <td>{produtos.codigo}</td>
              <td>{produtos.descricao}</td>
              <td>{produtos.marca}</td>
              <td>{produtos.tamanho}</td>
              <td>{produtos.quantidade}</td>
              <td>{produtos.precocusto}</td>
              <td>{produtos.precovenda}</td>
              <td>
                  
                  <Button size="sm" className={styles.button_Edit} variant="warning" onClick={()=>{update(dados)}}>
                     edit
                      </Button>

                  <Button size="sm" className={styles.button_Remove} variant="danger" onClick={()=>{remove(dados.id)}}>remove</Button>
                
              </td>
          
          </tr>
              )
   })
}

  return (
    <div>
      <Layout>
      <Head>
        <title>Interface Felipe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Funcionando
      {renderTable()}
      </Layout>
      
    

     
    </div>
  )
}
